#!/usr/bin/env node

const baseUrl = (process.env.LIVE_NEXUS_URL || "https://live.unite-group.ink").replace(
  /\/$/,
  ""
);
const runSave = process.env.LIVE_NEXUS_SMOKE_SAVE === "1";

async function request(path, init = {}) {
  const started = Date.now();
  const res = await fetch(`${baseUrl}${path}`, {
    ...init,
    headers: {
      "content-type": "application/json",
      ...(init.headers || {}),
    },
  });
  const elapsedMs = Date.now() - started;
  const text = await res.text();
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = text;
  }
  return { res, body, elapsedMs };
}

function assert(condition, message, detail) {
  if (!condition) {
    const suffix = detail ? `\n${JSON.stringify(detail, null, 2)}` : "";
    throw new Error(`${message}${suffix}`);
  }
}

function logPass(label, detail = "") {
  console.log(`PASS ${label}${detail ? ` - ${detail}` : ""}`);
}

const transcript =
  "We reviewed the Pricing proposal and Q2 numbers update. I will send the revised pricing proposal by Friday. Sarah will reconcile the Q2 numbers before Monday.";

try {
  const page = await request("/", { method: "GET", headers: {} });
  assert(page.res.ok, "Landing page did not return 2xx", {
    status: page.res.status,
    body: page.body,
  });
  logPass("landing", `${page.res.status} in ${page.elapsedMs}ms`);

  const session = await request("/api/session", { method: "POST", body: "{}" });
  assert(session.res.ok, "/api/session did not return 2xx", {
    status: session.res.status,
    body: session.body,
  });
  assert(typeof session.body?.token === "string" && session.body.token.length > 100, "Missing AssemblyAI token");
  assert(
    session.body?.ws_url === "wss://streaming.assemblyai.com/v3/ws",
    "Unexpected AssemblyAI websocket URL",
    session.body
  );
  logPass("/api/session", `v3 token length ${session.body.token.length}`);

  const synth = await request("/api/synthesize", {
    method: "POST",
    body: JSON.stringify({
      transcript,
      current_topics: [],
      current_actions: [],
    }),
  });
  assert(synth.res.ok, "/api/synthesize did not return 2xx", {
    status: synth.res.status,
    body: synth.body,
  });
  assert(Array.isArray(synth.body?.topics), "Synthesis topics are not an array", synth.body);
  assert(Array.isArray(synth.body?.actions), "Synthesis actions are not an array", synth.body);
  assert(
    synth.body.topics.includes("Pricing proposal") &&
      synth.body.topics.includes("Q2 numbers update"),
    "Synthesis topics did not include expected fixtures",
    synth.body
  );
  assert(synth.body.actions.length >= 2, "Synthesis did not return expected action count", synth.body);
  logPass("/api/synthesize", `${synth.body.topics.length} topics, ${synth.body.actions.length} actions`);

  if (runSave) {
    const timestamp = new Date().toISOString();
    const save = await request("/api/save", {
      method: "POST",
      body: JSON.stringify({
        meetingId: `prod-smoke-${timestamp}`,
        title: "Live Nexus Production Smoke Test Remove",
        startedAt: timestamp,
        endedAt: timestamp,
        transcript: [
          {
            timestamp: timestamp.slice(11, 16),
            speaker: "Codex",
            text: "Production smoke test for Live Nexus save endpoint.",
          },
        ],
        topics: ["Live Nexus production verification"],
        actions: [
          {
            title: "Remove smoke test file later",
            description: "Generated by live-nexus/scripts/prod-smoke.mjs.",
            priority: 4,
          },
        ],
        brand: "unite-group",
      }),
    });
    assert(save.res.ok, "/api/save did not return 2xx", {
      status: save.res.status,
      body: save.body,
    });
    assert(typeof save.body?.driveUrl === "string", "Save did not return a Drive URL", save.body);
    logPass("/api/save", save.body.driveUrl);
  } else {
    console.log("SKIP /api/save - set LIVE_NEXUS_SMOKE_SAVE=1 to create a Drive smoke file");
  }

  console.log(`GREEN Live Nexus production smoke passed for ${baseUrl}`);
} catch (error) {
  console.error(`RED Live Nexus production smoke failed for ${baseUrl}`);
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
