#!/usr/bin/env python3
"""file_length_lint.py — enforce the 300-line file convention as a ratchet.

WHY THIS EXISTS, AND WHY IT IS NOT RUFF
---------------------------------------
CLAUDE.md § Conventions states "files under 300". It was prose only: nothing
measured it, and 164 of 908 tracked Python files were already over when this
gate was written. A convention nothing checks is a preference, not a rule.

Ruff cannot do this. As of 0.15.x it ships 954 rules and none of them measures
file length -- pylint's `C0302 too-many-lines` is not among the ~115 `PL*`
rules ruff implements, and there is no `max-lines` setting. Ruff's size rules
are per-function (`PLR0915` statements, `C901` complexity), which is a
different measurement. Re-derive with:

    ruff rule --all --output-format json | python3 -c "import json,sys; \
      print([r['code'] for r in json.load(sys.stdin) if 'C0302' in str(r['code'])])"

So the limit lives here instead, and runs beside ruff in CI.

THE RATCHET
-----------
A hard limit would fail on 164 files the day it landed, so this grandfathers
what exists and stops it getting worse -- the same shape as
`.github/design-md-lint.baseline.txt`, which ratchets icon imports:

  FAIL  a file not in the baseline exceeds the limit      (no new offenders)
  FAIL  a file in the baseline grows beyond its entry     (no adding to them)
  WARN  a file in the baseline shrank                     (lower the baseline)

That is CLAUDE.md's own instruction -- "extract when you touch them; do not
add to them" -- made mechanical. The baseline only ever goes down.

USAGE
-----
    python3 .github/scripts/file_length_lint.py            # check (CI)
    python3 .github/scripts/file_length_lint.py --update   # rewrite baseline
    FILE_LENGTH_LIMIT=250 python3 ... --update             # tighten the limit

Scope is tracked `*.py`, `*.ts` and `*.tsx`, minus two exemptions -- generated
output and Remotion compositions. See GENERATED_PARTS / DOMAIN_EXEMPT_PARTS for
why each is exempt; the reasons differ and are recorded separately. The run
prints the exempt paths so nothing is ignored silently.
"""
from __future__ import annotations

import hashlib
import os
import subprocess
import sys
from pathlib import Path

LIMIT = int(os.environ.get("FILE_LENGTH_LIMIT", "300"))
SUFFIXES = ("*.py", "*.ts", "*.tsx")
# Two exemptions, kept apart because the reasons are not the same and merging them
# would make one of the comments false.
#
# NOT AUTHORED — no one to tell "split this". `node_modules` is vendored;
# `/dist/` is tsup output, tracked but rewritten by --clean on every build.
GENERATED_PARTS = ("node_modules/", "/dist/")
#
# AUTHORED, but long by the nature of the medium rather than by neglect. A
# Remotion composition is one declarative animation timeline; splitting it across
# files scatters a single frame-by-frame sequence for no reader's benefit. These
# were baselined at first, which implied a promise to shrink them that nobody
# intends to keep -- an exemption states the position honestly, where a baseline
# entry pretends it is debt. Note this covers `src/compositions/` only:
# `remotion-studio/scripts/` is ordinary code and stays governed.
DOMAIN_EXEMPT_PARTS = ("remotion-studio/src/compositions/",)

EXCLUDE_PARTS = GENERATED_PARTS + DOMAIN_EXEMPT_PARTS
BASELINE_PATH = Path(".github/file-length.baseline.txt")
# Emit GitHub Actions annotations when running inside Actions.
ANNOTATE = bool(os.environ.get("GITHUB_ACTIONS"))

_HEADER = """\
# File-length baseline — Pi-Dev-Ops
#
# Generated by .github/scripts/file_length_lint.py. Do not hand-edit: run
#     python3 .github/scripts/file_length_lint.py --update
#
# Every tracked .py/.ts/.tsx file over the {limit}-line convention in CLAUDE.md
# § Conventions, with the length it is grandfathered at. The gate fails when a
# file here GROWS past its entry, or when a file NOT here crosses the limit.
#
# This list is meant to shrink. When you extract from one of these files, run
# --update and commit the smaller number; when a file drops under {limit} the
# update removes it and it can never come back.
#
# format: <lines><TAB><content-fingerprint><TAB><path>
#
# The fingerprint is a hash of the file's bytes, so a pure `git mv` keeps it and
# an edit loses it. Move forgiveness matches on it, never on line count alone:
# baselined files repeat lengths often enough that equal length would let an
# unrelated new file inherit a deleted one's slot.
"""


def tracked_source_files() -> list[Path]:
    """Tracked source paths, per git. Untracked scratch files are not linted."""
    out = subprocess.run(
        ["git", "ls-files", *SUFFIXES],
        capture_output=True, text=True, check=True,
    ).stdout.split("\n")
    return [
        Path(p) for p in out
        if p and not any(part in f"/{p}" for part in EXCLUDE_PARTS)
    ]


def measure(path: Path) -> tuple[int, str]:
    """`(newline count, content fingerprint)`.

    The count matches `wc -l` so the two never disagree. The fingerprint is a
    hash of the bytes: a `git mv` leaves them identical, so a pure move keeps it
    and any edit loses it. Content rather than structure because this gate also
    covers `.ts`/`.tsx`, where there is no parser to hand.
    """
    try:
        raw = path.read_bytes()
    except OSError:
        return 0, ""
    return raw.count(b"\n"), hashlib.sha256(raw).hexdigest()[:12]


def read_baseline() -> dict[str, tuple[int, str]]:
    """`path -> (lines, fingerprint)`. Fingerprint is "" for pre-fingerprint rows."""
    if not BASELINE_PATH.exists():
        return {}
    entries: dict[str, tuple[int, str]] = {}
    for raw in BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 3:
            entries[parts[2].strip()] = (int(parts[0]), parts[1].strip())
        elif len(parts) == 2:
            entries[parts[1].strip()] = (int(parts[0]), "")
    return entries


def write_baseline(sizes: dict[str, tuple[int, str]]) -> None:
    over = {p: v for p, v in sizes.items() if v[0] > LIMIT}
    body = "".join(
        f"{n}\t{fp}\t{p}\n"
        for p, (n, fp) in sorted(over.items(), key=lambda kv: (-kv[1][0], kv[0]))
    )
    BASELINE_PATH.write_text(_HEADER.format(limit=LIMIT) + body, encoding="utf-8")
    print(f"wrote {BASELINE_PATH} — {len(over)} file(s) over {LIMIT} lines")


def annotate(path: str, message: str) -> None:
    if ANNOTATE:
        print(f"::error file={path}::{message}")


def classify(
    sizes: dict[str, tuple[int, str]], baseline: dict[str, tuple[int, str]]
) -> dict[str, list]:
    """Sort every measured file into new / grown / shrunk / moved.

    Move forgiveness matches on the CONTENT FINGERPRINT, not on length. An earlier
    version keyed it on line count alone, which is the same defect CodeRabbit found
    in the function gate: delete a baselined 310-line file, add an unrelated
    310-line one, and the new file inherited the old one's slot. Baselined files
    repeat lengths often enough for that to be reachable -- rarer than for
    functions, not absent.
    """
    missing = {p: v for p, v in baseline.items() if p not in sizes}
    movable: dict[str, int] = {}
    for _, fp in missing.values():
        if fp:  # pre-fingerprint rows cannot be matched, so they are never movable
            movable[fp] = movable.get(fp, 0) + 1

    out: dict[str, list] = {"new": [], "grown": [], "shrunk": [], "moved": []}
    for path, (count, fp) in sorted(sizes.items()):
        entry = baseline.get(path)
        if entry is None:
            if count > LIMIT:
                if movable.get(fp):
                    movable[fp] -= 1
                    out["moved"].append((path, count))
                else:
                    out["new"].append((path, count))
            continue
        allowed = entry[0]
        if count > allowed:
            out["grown"].append((path, allowed, count))
        elif count < allowed:
            out["shrunk"].append((path, allowed, count))
    return out


def report_failures(found: dict[str, list]) -> None:
    """Print failures and warnings, with GitHub annotations on the failures."""
    for path, count in found["new"]:
        msg = (f"{count} lines exceeds the {LIMIT}-line convention (CLAUDE.md "
               f"§ Conventions). Split it, or extract before adding here.")
        print(f"FAIL  {path}: {msg}")
        annotate(path, msg)

    for path, allowed, count in found["grown"]:
        msg = (f"grew from {allowed} to {count} lines, over the {LIMIT}-line "
               f"convention. CLAUDE.md: extract when you touch these; do not add to them.")
        print(f"FAIL  {path}: {msg}")
        annotate(path, msg)

    for path, count in found["moved"]:
        print(f"warn  {path}: {count} lines, byte-identical to a baselined file that "
              f"left the tree — treated as a move, not a new offender. Run --update.")
    for path, allowed, count in found["shrunk"]:
        print(f"warn  {path}: shrank {allowed} -> {count}; lower the baseline (--update)")


def main() -> int:
    if not Path(".git").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2

    sizes = {str(p): measure(p) for p in tracked_source_files()}
    if "--update" in sys.argv:
        write_baseline(sizes)
        return 0

    baseline = read_baseline()
    found = classify(sizes, baseline)
    report_failures(found)

    if found["new"] or found["grown"]:
        print(f"\nfile-length gate FAILED — {len(found['new'])} new offender(s), "
              f"{len(found['grown'])} grown.\n"
              f"Fix by extracting code, not by editing the baseline. If a split is "
              f"genuinely out of scope, say so in the PR and update the baseline "
              f"deliberately:\n"
              f"    python3 {BASELINE_PATH.parent}/scripts/file_length_lint.py --update")
        return 1

    exempt = sum(
        1 for line in subprocess.run(
            ["git", "ls-files", *SUFFIXES], capture_output=True, text=True, check=True,
        ).stdout.split("\n")
        if line and any(part in f"/{line}" for part in EXCLUDE_PARTS)
    )
    print(f"file-length gate passed — {len(sizes)} tracked source files, "
          f"{len(baseline)} grandfathered over {LIMIT} lines, 0 new, 0 grown.")
    if exempt:
        print(f"{exempt} file(s) exempt, not merely grandfathered: "
              f"{', '.join(EXCLUDE_PARTS)}")
    if found["shrunk"]:
        print(f"{len(found['shrunk'])} file(s) shrank — run --update to ratchet the baseline down.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
