#!/usr/bin/env python3
"""file_length_lint.py — enforce the 300-line file convention as a ratchet.

WHY THIS EXISTS, AND WHY IT IS NOT RUFF
---------------------------------------
CLAUDE.md § Conventions states "files under 300". It was prose only: nothing
measured it, and 164 of 908 tracked Python files were already over when this
gate was written. A convention nothing checks is a preference, not a rule.

Ruff cannot do this. As of 0.15.x it ships 954 rules and none of them measures
file length -- pylint's `C0302 too-many-lines` is not among the ~115 `PL*`
rules ruff implements, and there is no `max-lines` setting. Ruff's size rules
are per-function (`PLR0915` statements, `C901` complexity), which is a
different measurement. Re-derive with:

    ruff rule --all --output-format json | python3 -c "import json,sys; \
      print([r['code'] for r in json.load(sys.stdin) if 'C0302' in str(r['code'])])"

So the limit lives here instead, and runs beside ruff in CI.

THE RATCHET
-----------
A hard limit would fail on 164 files the day it landed, so this grandfathers
what exists and stops it getting worse -- the same shape as
`.github/design-md-lint.baseline.txt`, which ratchets icon imports:

  FAIL  a file not in the baseline exceeds the limit      (no new offenders)
  FAIL  a file in the baseline grows beyond its entry     (no adding to them)
  WARN  a file in the baseline shrank                     (lower the baseline)

That is CLAUDE.md's own instruction -- "extract when you touch them; do not
add to them" -- made mechanical. The baseline only ever goes down.

USAGE
-----
    python3 .github/scripts/file_length_lint.py            # check (CI)
    python3 .github/scripts/file_length_lint.py --update   # rewrite baseline
    FILE_LENGTH_LIMIT=250 python3 ... --update             # tighten the limit

Scope is tracked `*.py`, matching ruff's domain. TypeScript is not covered.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

LIMIT = int(os.environ.get("FILE_LENGTH_LIMIT", "300"))
BASELINE_PATH = Path(".github/file-length.baseline.txt")
# Emit GitHub Actions annotations when running inside Actions.
ANNOTATE = bool(os.environ.get("GITHUB_ACTIONS"))

_HEADER = """\
# File-length baseline — Pi-Dev-Ops
#
# Generated by .github/scripts/file_length_lint.py. Do not hand-edit: run
#     python3 .github/scripts/file_length_lint.py --update
#
# Every tracked .py file over the {limit}-line convention in CLAUDE.md
# § Conventions, with the length it is grandfathered at. The gate fails when a
# file here GROWS past its entry, or when a file NOT here crosses the limit.
#
# This list is meant to shrink. When you extract from one of these files, run
# --update and commit the smaller number; when a file drops under {limit} the
# update removes it and it can never come back.
#
# format: <lines><TAB><path>
"""


def tracked_python_files() -> list[Path]:
    """Tracked `*.py` paths, per git. Untracked scratch files are not linted."""
    out = subprocess.run(
        ["git", "ls-files", "*.py"],
        capture_output=True, text=True, check=True,
    ).stdout.split("\n")
    return [Path(p) for p in out if p and "node_modules" not in p]


def line_count(path: Path) -> int:
    """Newline count, matching `wc -l` so the two never disagree."""
    try:
        with path.open("rb") as fh:
            return fh.read().count(b"\n")
    except OSError:
        return 0


def read_baseline() -> dict[str, int]:
    if not BASELINE_PATH.exists():
        return {}
    entries: dict[str, int] = {}
    for raw in BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        count, _, path = line.partition("\t")
        if path:
            entries[path.strip()] = int(count.strip())
    return entries


def write_baseline(sizes: dict[str, int]) -> None:
    over = {p: n for p, n in sizes.items() if n > LIMIT}
    body = "".join(
        f"{n}\t{p}\n" for p, n in sorted(over.items(), key=lambda kv: (-kv[1], kv[0]))
    )
    BASELINE_PATH.write_text(_HEADER.format(limit=LIMIT) + body, encoding="utf-8")
    print(f"wrote {BASELINE_PATH} — {len(over)} file(s) over {LIMIT} lines")


def annotate(path: str, message: str) -> None:
    if ANNOTATE:
        print(f"::error file={path}::{message}")


def main() -> int:
    if not Path(".git").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2

    sizes = {str(p): line_count(p) for p in tracked_python_files()}

    if "--update" in sys.argv:
        write_baseline(sizes)
        return 0

    baseline = read_baseline()
    new_offenders: list[tuple[str, int]] = []
    grown: list[tuple[str, int, int]] = []
    shrunk: list[tuple[str, int, int]] = []

    for path, count in sorted(sizes.items()):
        allowed = baseline.get(path)
        if allowed is None:
            if count > LIMIT:
                new_offenders.append((path, count))
        elif count > allowed:
            grown.append((path, allowed, count))
        elif count < allowed:
            shrunk.append((path, allowed, count))

    for path, count in new_offenders:
        msg = (
            f"{count} lines exceeds the {LIMIT}-line convention (CLAUDE.md "
            f"§ Conventions). Split it, or extract before adding here."
        )
        print(f"FAIL  {path}: {msg}")
        annotate(path, msg)

    for path, allowed, count in grown:
        msg = (
            f"grew from {allowed} to {count} lines, over the {LIMIT}-line "
            f"convention. CLAUDE.md: extract when you touch these; do not add to them."
        )
        print(f"FAIL  {path}: {msg}")
        annotate(path, msg)

    for path, allowed, count in shrunk:
        print(f"warn  {path}: shrank {allowed} -> {count}; lower the baseline (--update)")

    failures = len(new_offenders) + len(grown)
    if failures:
        print(
            f"\nfile-length gate FAILED — {len(new_offenders)} new offender(s), "
            f"{len(grown)} grown.\n"
            f"Fix by extracting code, not by editing the baseline. If a split is "
            f"genuinely out of scope, say so in the PR and update the baseline "
            f"deliberately:\n"
            f"    python3 {BASELINE_PATH.parent / 'scripts/file_length_lint.py'} --update"
        )
        return 1

    grandfathered = len(baseline)
    print(
        f"file-length gate passed — {len(sizes)} tracked .py files, "
        f"{grandfathered} grandfathered over {LIMIT} lines, 0 new, 0 grown."
    )
    if shrunk:
        print(f"{len(shrunk)} file(s) shrank — run --update to ratchet the baseline down.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
