#!/usr/bin/env python3
"""function_length_lint.py — enforce the 40-line function convention as a ratchet.

WHY NOT PLR0915
---------------
CLAUDE.md § Conventions says "functions under 40 lines". Ruff's nearest rule,
`PLR0915 too-many-statements`, counts STATEMENTS, and on this codebase the two
measurements barely correlate. A snapshot over 8922 tracked functions, 614 of
which exceed 40 lines -- the shape is the argument, not the exact figures,
which drift as the tree changes:

    max-statements=50 (ruff default)  catches   65/614 =  10%    0 false hits
    max-statements=40                 catches  118/614 =  19%    0 false hits
    max-statements=30                 catches  224/614 =  36%    6 false hits
    max-statements=20                 catches  428/614 =  69%  187 false hits

There is no setting that works: loose thresholds miss ~90% of the functions the
convention is about, and the threshold that catches most of them flags 183
functions that are already compliant. The cause is visible in the outliers --
`session_sdk._run_claude_via_sdk` is 280 lines but only 88 statements. Long
functions here are line-heavy and statement-light: multi-line calls, dict
literals, long string arguments. Statements are a fine complexity signal and a
poor length one.

So this measures what the convention actually says, by walking the AST. Enabling
PLR0915 as well is a separate, defensible decision -- it would be enforcing
complexity, not length, and needs its own baseline.

Re-derive the table above with `--report`.

THE RATCHET
-----------
Same shape as file_length_lint.py, for the same reason: hundreds of pre-existing
violations mean a hard limit fails everything on day one.

  FAIL  a function not in the baseline exceeds the limit
  FAIL  a function in the baseline grows beyond its entry
  WARN  a baselined function shrank (lower it), or moved -- matched on a
        structural hash of its body, never on line count alone. The baselined
        functions share barely a hundred distinct lengths between them, so equal
        length is no evidence of identity -- see classify() for the command.

USAGE
-----
    python3 .github/scripts/function_length_lint.py            # check (CI)
    python3 .github/scripts/function_length_lint.py --update   # rewrite baseline
    python3 .github/scripts/function_length_lint.py --report   # PLR0915 comparison
    FUNCTION_LENGTH_LIMIT=30 python3 ... --update               # tighten

Python only: this walks `ast`, and TypeScript would need its own parser.
Baseline key is `path::qualname`, verified unique across all 8910 functions.
"""
from __future__ import annotations

import ast
import hashlib
import os
import subprocess
import sys
from pathlib import Path

# (lines, lineno, body fingerprint)
Fn = tuple[int, int, str]

LIMIT = int(os.environ.get("FUNCTION_LENGTH_LIMIT", "40"))
EXCLUDE_PARTS = ("node_modules/", "/dist/")
BASELINE_PATH = Path(".github/function-length.baseline.txt")
ANNOTATE = bool(os.environ.get("GITHUB_ACTIONS"))

_HEADER = """\
# Function-length baseline — Pi-Dev-Ops
#
# Generated by .github/scripts/function_length_lint.py. Do not hand-edit: run
#     python3 .github/scripts/function_length_lint.py --update
#
# Every tracked Python function over the {limit}-line convention in CLAUDE.md
# § Conventions, with the length it is grandfathered at. The gate fails when one
# here GROWS past its entry, or when a function NOT here crosses the limit.
#
# Fix by extracting, then --update and commit the smaller number. Never raise an
# entry to get green -- that defeats the only thing this file does.
#
# format: <lines><TAB><body-fingerprint><TAB><path>::<qualname>
#
# The fingerprint is a structural hash of the function BODY, name excluded, so a
# rename or move keeps it and an edit loses it. Rename forgiveness matches on it
# rather than on length: these functions share barely a hundred distinct lengths
# between them, so length alone would let an unrelated new function inherit a
# deleted one's slot.
"""


def tracked_python_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "*.py"], capture_output=True, text=True, check=True,
    ).stdout.split("\n")
    return [p for p in out if p and not any(x in f"/{p}" for x in EXCLUDE_PARTS)]


def _fingerprint(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Structural hash of the BODY, excluding the name.

    Excluding the name is the point: a renamed or moved function keeps its
    fingerprint, while an edited one loses it. Structural rather than textual so
    reformatting and comment edits do not read as a rewrite.
    """
    dumped = "".join(ast.dump(stmt) for stmt in node.body)
    return hashlib.sha256(dumped.encode("utf-8")).hexdigest()[:12]


def _walk(node: ast.AST, prefix: str, path: str, out: dict[str, Fn]) -> None:
    """Collect `path::qualname -> (lines, lineno, fingerprint)`, nested included."""
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            qual = f"{prefix}.{child.name}" if prefix else child.name
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)) and child.end_lineno:
                # Span of the def, decorators excluded: they are not body length.
                out[f"{path}::{qual}"] = (
                    child.end_lineno - child.lineno + 1,
                    child.lineno,
                    _fingerprint(child),
                )
            _walk(child, qual, path, out)
        else:
            _walk(child, prefix, path, out)


def measure() -> tuple[dict[str, Fn], list[str]]:
    """Every function's length, plus the files that could not be parsed."""
    sizes: dict[str, Fn] = {}
    unparsed: list[str] = []
    for path in tracked_python_files():
        try:
            tree = ast.parse(Path(path).read_text(encoding="utf-8"))
        except (SyntaxError, OSError, UnicodeDecodeError):
            unparsed.append(path)
            continue
        _walk(tree, "", path, sizes)
    return sizes, unparsed


def read_baseline() -> dict[str, tuple[int, str]]:
    """`key -> (lines, fingerprint)`. Fingerprint is "" for pre-fingerprint rows."""
    if not BASELINE_PATH.exists():
        return {}
    entries: dict[str, tuple[int, str]] = {}
    for raw in BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 3:
            entries[parts[2].strip()] = (int(parts[0]), parts[1].strip())
        elif len(parts) == 2:
            entries[parts[1].strip()] = (int(parts[0]), "")
    return entries


def write_baseline(sizes: dict[str, Fn]) -> None:
    over = {k: (v[0], v[2]) for k, v in sizes.items() if v[0] > LIMIT}
    body = "".join(
        f"{n}\t{fp}\t{k}\n"
        for k, (n, fp) in sorted(over.items(), key=lambda kv: (-kv[1][0], kv[0]))
    )
    BASELINE_PATH.write_text(_HEADER.format(limit=LIMIT) + body, encoding="utf-8")
    print(f"wrote {BASELINE_PATH} — {len(over)} function(s) over {LIMIT} lines")


def report() -> int:
    """Re-derive the PLR0915 comparison in this module's docstring."""
    sizes, _ = measure()
    stmt_counts: dict[str, int] = {}
    for path in tracked_python_files():
        try:
            tree = ast.parse(Path(path).read_text(encoding="utf-8"))
        except (SyntaxError, OSError, UnicodeDecodeError):
            continue
        collected: dict[str, tuple[int, int]] = {}
        _walk(tree, "", path, collected)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                n = sum(1 for x in ast.walk(node) if isinstance(x, ast.stmt)) - 1
                for key, meta in collected.items():
                    if meta[1] == node.lineno:
                        stmt_counts[key] = n
    over = {k for k, v in sizes.items() if v[0] > LIMIT}
    print(f"functions: {len(sizes)} | over {LIMIT} lines: {len(over)}")
    for thr in (50, 40, 30, 20):
        caught = sum(1 for k in over if stmt_counts.get(k, 0) > thr)
        false = sum(
            1 for k, v in sizes.items()
            if v[0] <= LIMIT and stmt_counts.get(k, 0) > thr
        )
        pct = 100 * caught // len(over) if over else 0
        print(f"  max-statements={thr:<3} catches {caught:>4}/{len(over)} = {pct:>3}%  "
              f"| flags {false} already-compliant")
    return 0


def classify(sizes: dict[str, Fn], baseline: dict[str, tuple[int, str]]) -> dict[str, list]:
    """Sort every measured function into new / grown / shrunk / moved.

    Rename forgiveness matches on the BODY FINGERPRINT, not on length. An earlier
    draft keyed it on line count alone, which CodeRabbit correctly flagged: delete
    a baselined 41-line function, add an unrelated 41-line one, and the new one
    inherited the old one's slot silently. That is not a rare collision here --
    the baselined functions share barely a hundred distinct lengths between them,
    dozens sharing the single most common value. A fingerprint match means the
    same body really did move. Re-derive the spread with:

        python3 -c "import collections; lens=[int(l.split(chr(9))[0]) for l in
          open('.github/function-length.baseline.txt') if not l.startswith('#')
          and l.strip()]; print(len(lens), len(collections.Counter(lens)))"
    """
    missing = {k: v for k, v in baseline.items() if k not in sizes}
    movable: dict[str, int] = {}
    for _, fp in missing.values():
        if fp:  # pre-fingerprint rows cannot be matched, so they are never movable
            movable[fp] = movable.get(fp, 0) + 1

    out: dict[str, list] = {"new": [], "grown": [], "shrunk": [], "moved": []}
    for key, (count, lineno, fp) in sorted(sizes.items()):
        entry = baseline.get(key)
        if entry is None:
            if count > LIMIT:
                if movable.get(fp):
                    movable[fp] -= 1
                    out["moved"].append((key, count))
                else:
                    out["new"].append((key, count, lineno))
            continue
        allowed = entry[0]
        if count > allowed:
            out["grown"].append((key, allowed, count, lineno))
        elif count < allowed:
            out["shrunk"].append((key, allowed, count))
    return out


def report_failures(found: dict[str, list]) -> None:
    """Print failures, with GitHub annotations pinned to the def's line."""
    for key, count, lineno in found["new"]:
        path, name = key.split("::", 1)
        print(f"FAIL  {key}: {count} lines")
        if ANNOTATE:
            print(f"::error file={path},line={lineno}::{name}() is {count} lines, over "
                  f"the {LIMIT}-line convention (CLAUDE.md § Conventions). Extract a helper.")

    for key, allowed, count, lineno in found["grown"]:
        path, name = key.split("::", 1)
        print(f"FAIL  {key}: grew {allowed} -> {count}")
        if ANNOTATE:
            print(f"::error file={path},line={lineno}::{name}() grew {allowed} -> {count} "
                  f"lines. CLAUDE.md: extract when you touch these; do not add to them.")

    for key, count in found["moved"]:
        print(f"warn  {key}: {count} lines, matches a baselined function that "
              f"disappeared — treated as a rename. Run --update.")
    for key, allowed, count in found["shrunk"]:
        print(f"warn  {key}: shrank {allowed} -> {count}; lower the baseline (--update)")


def main() -> int:
    if not Path(".git").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2
    if "--report" in sys.argv:
        return report()

    sizes, unparsed = measure()
    if "--update" in sys.argv:
        write_baseline(sizes)
        if unparsed:
            print(f"note: {len(unparsed)} file(s) did not parse and were skipped")
        return 0

    baseline = read_baseline()
    found = classify(sizes, baseline)
    report_failures(found)

    if found["new"] or found["grown"]:
        print(f"\nfunction-length gate FAILED — {len(found['new'])} new, "
              f"{len(found['grown'])} grown.\n"
              f"Fix by extracting, not by editing the baseline:\n"
              f"    python3 {BASELINE_PATH.parent}/scripts/function_length_lint.py --update")
        return 1

    print(f"function-length gate passed — {len(sizes)} functions, "
          f"{len(baseline)} grandfathered over {LIMIT} lines, 0 new, 0 grown.")
    if unparsed:
        print(f"{len(unparsed)} file(s) did not parse and were skipped: {', '.join(unparsed[:3])}")
    if found["shrunk"]:
        print(f"{len(found['shrunk'])} function(s) shrank — run --update to ratchet down.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
