#!/usr/bin/env python3
"""function_length_lint.py — enforce the 40-line function convention as a ratchet.

WHY NOT PLR0915
---------------
CLAUDE.md § Conventions says "functions under 40 lines". Ruff's nearest rule,
`PLR0915 too-many-statements`, counts STATEMENTS, and on this codebase the two
measurements barely correlate. Measured over 8910 tracked functions, 615 of
which exceed 40 lines:

    max-statements=50 (ruff default)  catches   66/615 =  10%   0 false hits
    max-statements=40                 catches  119/615 =  19%   0 false hits
    max-statements=30                 catches  225/615 =  36%   6 false hits
    max-statements=20                 catches  429/615 =  69% 183 false hits

There is no setting that works: loose thresholds miss ~90% of the functions the
convention is about, and the threshold that catches most of them flags 183
functions that are already compliant. The cause is visible in the outliers --
`session_sdk._run_claude_via_sdk` is 280 lines but only 88 statements. Long
functions here are line-heavy and statement-light: multi-line calls, dict
literals, long string arguments. Statements are a fine complexity signal and a
poor length one.

So this measures what the convention actually says, by walking the AST. Enabling
PLR0915 as well is a separate, defensible decision -- it would be enforcing
complexity, not length, and needs its own baseline.

Re-derive the table above with `--report`.

THE RATCHET
-----------
Same shape as file_length_lint.py, for the same reason: 615 pre-existing
violations means a hard limit fails everything on day one.

  FAIL  a function not in the baseline exceeds the limit
  FAIL  a function in the baseline grows beyond its entry
  WARN  a baselined function shrank (lower it) or moved (same size, new name)

USAGE
-----
    python3 .github/scripts/function_length_lint.py            # check (CI)
    python3 .github/scripts/function_length_lint.py --update   # rewrite baseline
    python3 .github/scripts/function_length_lint.py --report   # PLR0915 comparison
    FUNCTION_LENGTH_LIMIT=30 python3 ... --update               # tighten

Python only: this walks `ast`, and TypeScript would need its own parser.
Baseline key is `path::qualname`, verified unique across all 8910 functions.
"""
from __future__ import annotations

import ast
import os
import subprocess
import sys
from pathlib import Path

LIMIT = int(os.environ.get("FUNCTION_LENGTH_LIMIT", "40"))
EXCLUDE_PARTS = ("node_modules/", "/dist/")
BASELINE_PATH = Path(".github/function-length.baseline.txt")
ANNOTATE = bool(os.environ.get("GITHUB_ACTIONS"))

_HEADER = """\
# Function-length baseline — Pi-Dev-Ops
#
# Generated by .github/scripts/function_length_lint.py. Do not hand-edit: run
#     python3 .github/scripts/function_length_lint.py --update
#
# Every tracked Python function over the {limit}-line convention in CLAUDE.md
# § Conventions, with the length it is grandfathered at. The gate fails when one
# here GROWS past its entry, or when a function NOT here crosses the limit.
#
# Fix by extracting, then --update and commit the smaller number. Never raise an
# entry to get green -- that defeats the only thing this file does.
#
# format: <lines><TAB><path>::<qualname>
"""


def tracked_python_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "*.py"], capture_output=True, text=True, check=True,
    ).stdout.split("\n")
    return [p for p in out if p and not any(x in f"/{p}" for x in EXCLUDE_PARTS)]


def _walk(node: ast.AST, prefix: str, path: str, out: dict[str, tuple[int, int]]) -> None:
    """Collect `path::qualname -> (lines, lineno)` for every function, nested included."""
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            qual = f"{prefix}.{child.name}" if prefix else child.name
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)) and child.end_lineno:
                # Span of the def, decorators excluded: they are not body length.
                out[f"{path}::{qual}"] = (
                    child.end_lineno - child.lineno + 1,
                    child.lineno,
                )
            _walk(child, qual, path, out)
        else:
            _walk(child, prefix, path, out)


def measure() -> tuple[dict[str, tuple[int, int]], list[str]]:
    """Every function's length, plus the files that could not be parsed."""
    sizes: dict[str, tuple[int, int]] = {}
    unparsed: list[str] = []
    for path in tracked_python_files():
        try:
            tree = ast.parse(Path(path).read_text(encoding="utf-8"))
        except (SyntaxError, OSError, UnicodeDecodeError):
            unparsed.append(path)
            continue
        _walk(tree, "", path, sizes)
    return sizes, unparsed


def read_baseline() -> dict[str, int]:
    if not BASELINE_PATH.exists():
        return {}
    entries: dict[str, int] = {}
    for raw in BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        count, _, key = line.partition("\t")
        if key:
            entries[key.strip()] = int(count.strip())
    return entries


def write_baseline(sizes: dict[str, tuple[int, int]]) -> None:
    over = {k: v[0] for k, v in sizes.items() if v[0] > LIMIT}
    body = "".join(
        f"{n}\t{k}\n" for k, n in sorted(over.items(), key=lambda kv: (-kv[1], kv[0]))
    )
    BASELINE_PATH.write_text(_HEADER.format(limit=LIMIT) + body, encoding="utf-8")
    print(f"wrote {BASELINE_PATH} — {len(over)} function(s) over {LIMIT} lines")


def report() -> int:
    """Re-derive the PLR0915 comparison in this module's docstring."""
    sizes, _ = measure()
    stmt_counts: dict[str, int] = {}
    for path in tracked_python_files():
        try:
            tree = ast.parse(Path(path).read_text(encoding="utf-8"))
        except (SyntaxError, OSError, UnicodeDecodeError):
            continue
        collected: dict[str, tuple[int, int]] = {}
        _walk(tree, "", path, collected)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                n = sum(1 for x in ast.walk(node) if isinstance(x, ast.stmt)) - 1
                for key, (_, lineno) in collected.items():
                    if lineno == node.lineno:
                        stmt_counts[key] = n
    over = {k for k, v in sizes.items() if v[0] > LIMIT}
    print(f"functions: {len(sizes)} | over {LIMIT} lines: {len(over)}")
    for thr in (50, 40, 30, 20):
        caught = sum(1 for k in over if stmt_counts.get(k, 0) > thr)
        false = sum(
            1 for k, v in sizes.items()
            if v[0] <= LIMIT and stmt_counts.get(k, 0) > thr
        )
        pct = 100 * caught // len(over) if over else 0
        print(f"  max-statements={thr:<3} catches {caught:>4}/{len(over)} = {pct:>3}%  "
              f"| flags {false} already-compliant")
    return 0


def classify(
    sizes: dict[str, tuple[int, int]], baseline: dict[str, int]
) -> dict[str, list]:
    """Sort every measured function into new / grown / shrunk / moved.

    Rename forgiveness matches file_length_lint.py: a renamed or moved function
    leaves its baseline key and arrives under a new one, which would otherwise
    read as a new violation and tell the author to split code they only moved.
    """
    missing = {k: n for k, n in baseline.items() if k not in sizes}
    movable: dict[int, int] = {}
    for n in missing.values():
        movable[n] = movable.get(n, 0) + 1

    out: dict[str, list] = {"new": [], "grown": [], "shrunk": [], "moved": []}
    for key, (count, lineno) in sorted(sizes.items()):
        allowed = baseline.get(key)
        if allowed is None:
            if count > LIMIT:
                if movable.get(count):
                    movable[count] -= 1
                    out["moved"].append((key, count))
                else:
                    out["new"].append((key, count, lineno))
        elif count > allowed:
            out["grown"].append((key, allowed, count, lineno))
        elif count < allowed:
            out["shrunk"].append((key, allowed, count))
    return out


def report_failures(found: dict[str, list]) -> None:
    """Print failures, with GitHub annotations pinned to the def's line."""
    for key, count, lineno in found["new"]:
        path, name = key.split("::", 1)
        print(f"FAIL  {key}: {count} lines")
        if ANNOTATE:
            print(f"::error file={path},line={lineno}::{name}() is {count} lines, over "
                  f"the {LIMIT}-line convention (CLAUDE.md § Conventions). Extract a helper.")

    for key, allowed, count, lineno in found["grown"]:
        path, name = key.split("::", 1)
        print(f"FAIL  {key}: grew {allowed} -> {count}")
        if ANNOTATE:
            print(f"::error file={path},line={lineno}::{name}() grew {allowed} -> {count} "
                  f"lines. CLAUDE.md: extract when you touch these; do not add to them.")

    for key, count in found["moved"]:
        print(f"warn  {key}: {count} lines, matches a baselined function that "
              f"disappeared — treated as a rename. Run --update.")
    for key, allowed, count in found["shrunk"]:
        print(f"warn  {key}: shrank {allowed} -> {count}; lower the baseline (--update)")


def main() -> int:
    if not Path(".git").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2
    if "--report" in sys.argv:
        return report()

    sizes, unparsed = measure()
    if "--update" in sys.argv:
        write_baseline(sizes)
        if unparsed:
            print(f"note: {len(unparsed)} file(s) did not parse and were skipped")
        return 0

    baseline = read_baseline()
    found = classify(sizes, baseline)
    report_failures(found)

    if found["new"] or found["grown"]:
        print(f"\nfunction-length gate FAILED — {len(found['new'])} new, "
              f"{len(found['grown'])} grown.\n"
              f"Fix by extracting, not by editing the baseline:\n"
              f"    python3 {BASELINE_PATH.parent}/scripts/function_length_lint.py --update")
        return 1

    print(f"function-length gate passed — {len(sizes)} functions, "
          f"{len(baseline)} grandfathered over {LIMIT} lines, 0 new, 0 grown.")
    if unparsed:
        print(f"{len(unparsed)} file(s) did not parse and were skipped: {', '.join(unparsed[:3])}")
    if found["shrunk"]:
        print(f"{len(found['shrunk'])} function(s) shrank — run --update to ratchet down.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
