"""RA-1183 — open a pull request for the branch `_phase_push` just pushed.

Extracted from `session_phases._phase_push` so that neither `session_phases.py`
nor `_phase_push` grows past its length baseline. The move is behaviour-preserving
and `tests/test_phase_push_auto_pr.py` is the instrument that says so: that file
was written against the pre-move code, watched failing on three planted defects,
and passes unchanged on both sides of this extraction.

`run_cmd`, `em` and `route_linear` are passed in rather than imported, to avoid a
circular import back into session_phases and to leave the caller as the one place
that decides which implementations are in play.

Every failure here is swallowed by design. By the time this runs the code is
already pushed; a PR is a convenience on top of that, and losing it must not turn
a successful push into a failed one.
"""
from __future__ import annotations

import json
import urllib.request


def derive_owner_repo(remote_url: str, github_token: str) -> str:
    """`https://github.com/o/r.git` -> `o/r`.

    Also strips leftover `x-access-token` userinfo. Push no longer rewrites the
    remote; the strip stays so an old rewritten URL cannot leak the credential
    into the PR URL or `session.repo_name`.
    """
    ru = remote_url.strip().rstrip("/")
    ru = ru.replace(f"https://x-access-token:{github_token}@", "https://")
    if ru.endswith(".git"):
        ru = ru[:-4]
    return ru.replace("https://github.com/", "")


def _build_request(owner_repo: str, branch_name: str, pr_title: str,
                   pr_body: str, github_token: str) -> urllib.request.Request:
    return urllib.request.Request(
        f"https://api.github.com/repos/{owner_repo}/pulls",
        data=json.dumps({
            "title": pr_title,
            "body": pr_body,
            "head": branch_name,
            "base": "main",
        }).encode(),
        headers={
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        },
        method="POST",
    )


def _pr_body(session) -> str:
    """Requirement → Change → Test. A10 of the UNI-2652 golden journey reads this."""
    files = getattr(session, "modified_files", []) or []
    change = ", ".join(str(f) for f in files[:20]) or "see branch diff"
    plan = (getattr(session, "plan", "") or "").strip()
    requirement = plan.splitlines()[0] if plan else f"Autonomous session `{session.id}`"
    score = getattr(session, "evaluator_score", "n/a")
    tested = "yes" if getattr(session, "tests_passed", None) is True else "not evidenced"
    return (
        f"## Requirement\n{requirement}\n\n"
        f"## Change\n{change}\n\n"
        f"## Test\nEvaluator {score}/10; tests_passed={tested}.\n\n"
        f"Session `{session.id}`.\n\n"
        f"🤖 Generated by Pi-CEO"
    )


def _stamp_attribution(session, pr_url: str, pr_number, branch_name: str, owner_repo: str) -> None:
    """RA-7216 gap 2 — carry the attribution keys on the session.

    `pr_number` was once read and discarded as a local, so a merge event had
    nothing to match a `gate_checks` row by. These ride on the session rather than
    widening `_phase_push`'s return tuple, which several callers unpack.
    """
    # Two try blocks, deliberately, exactly as before the extraction. Collapsing
    # them into one looks like tidying and is a behaviour change: a raising
    # pr_url setter would then take the three attribution keys down with it, and
    # a merge event would have nothing to match its gate_checks row by. Caught by
    # independent review after the extraction claimed to be behaviour-preserving;
    # tests/test_phase_push_auto_pr.py now fails if they are merged again.
    try:
        session.pr_url = pr_url          # type: ignore[attr-defined]
    except Exception:
        pass
    try:
        session.pr_number = pr_number    # type: ignore[attr-defined]
        session.head_branch = branch_name  # type: ignore[attr-defined]
        session.repo_name = owner_repo   # type: ignore[attr-defined]
    except Exception:
        pass


def _handle_opened(session, em, route_linear, pr_data: dict,
                   branch_name: str, owner_repo: str, pr_title: str) -> None:
    pr_url = pr_data.get("html_url", "")
    pr_number = pr_data.get("number")
    em(session, "success", f"  ✨ PR opened: #{pr_number} → {pr_url}")
    _stamp_attribution(session, pr_url, pr_number, branch_name, owner_repo)

    # RA-1184 — route the Linear ticket to the TARGET repo's project, not
    # Pi-Dev-Ops. Only when we do not already have one.
    if getattr(session, "linear_issue_id", None):
        return
    try:
        route_linear(session, owner_repo, pr_url, pr_number, pr_title)
    except Exception as _lin_exc:
        em(session, "system", f"  Linear auto-ticket skipped: {_lin_exc}")


async def open_pull_request(session, run_cmd, em, route_linear, branch_name, github_token) -> None:
    """Open a PR from `branch_name` → main, when it carries a real diff.

    The diff check avoids empty PRs from sessions that correctly decided nothing
    needed fixing. Git auth is process-scoped (`git_auth_env`); the token here
    is the GitHub API Bearer header only.
    """
    try:
        rc_diff, diff_out, _ = await run_cmd(
            session.workspace, "git", "diff", "--name-only", "origin/main", branch_name, timeout=10,
        )
        if not (rc_diff == 0 and diff_out.strip()):
            em(session, "system", "  No diff vs main — skipping PR open")
            return

        _, ru, _ = await run_cmd(session.workspace, "git", "remote", "get-url", "origin", timeout=5)
        owner_repo = derive_owner_repo(ru, github_token)
        _, last_msg, _ = await run_cmd(
            session.workspace, "git", "log", "-1", "--pretty=%s", branch_name, timeout=5,
        )
        pr_title = last_msg.strip() or f"feat: Pi CEO autonomous fix ({session.id[:8]})"
        req = _build_request(owner_repo, branch_name, pr_title, _pr_body(session), github_token)
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                _handle_opened(session, em, route_linear, json.loads(resp.read()),
                               branch_name, owner_repo, pr_title)
        except Exception as _pr_exc:
            em(session, "system", f"  PR auto-open skipped: {_pr_exc}")
    except Exception as _pr_err:
        em(session, "system", f"  PR auto-open check failed: {_pr_err}")
