"""tests/test_provider_router_margot_casual_ladder.py — RA-7434.

Founder ruling (03/09/2026): ``margot.casual`` (the Telegram persona) runs on a
fixed free ladder — Ollama gemma4 → OpenRouter gemma free → OpenRouter GLM
flash — never Kimi, never an Anthropic model. Every other role keeps the
resolution it had before this change, byte for byte; the snapshot test at the
bottom is the control for that claim.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from app.server import provider_router as PR  # noqa: E402

SNAPSHOT_PATH = REPO_ROOT / "tests" / "fixtures" / "provider_router_roles_before_ra7434.json"

_ROUTER_ENV = (
    "TAO_TOP_MODEL", "TAO_MID_MODEL",
    "TAO_CHEAP_MODEL", "TAO_CHEAP_PROVIDER",
    "TAO_CHEAP_LOCAL_MODEL", "TAO_CHEAP_REMOTE_MODEL",
    "TAO_TOP_USE_CLAUDE_PRINT", "TAO_MID_USE_CLAUDE_PRINT",
    "OLLAMA_BASE_URL", "MARGOT_OLLAMA_BASE_URL",
)


def _ollama_module():
    mod = sys.modules.get("app.server.provider_ollama")
    if mod is None:
        from app.server import provider_ollama as mod  # noqa: PLC0415
    return mod


@pytest.fixture(autouse=True)
def _clean_env(monkeypatch):
    for k in _ROUTER_ENV:
        monkeypatch.delenv(k, raising=False)
    for k in list(os.environ):
        if k.startswith("TAO_MODEL_"):
            monkeypatch.delenv(k, raising=False)
    monkeypatch.setattr(_ollama_module(), "is_reachable", lambda **kw: False)
    # The downgrade recorder appends to a violations file; keep the test inert.
    monkeypatch.setattr(PR, "_record_tier_downgrade", lambda *a, **kw: None)


# ── Every other role: snapshot before == after ──────────────────────────────
#
# The fixture was generated by running ``snapshot()`` against provider_router
# at origin/main c810ef0b (before the margot.casual change). Regenerate ONLY
# when another role's routing is deliberately changed:
#   python -c "import json,tests.test_provider_router_margot_casual_ladder as t;
#              print(json.dumps(t.snapshot(), indent=2, sort_keys=True))"

SCENARIOS: dict[str, tuple[dict[str, str], bool]] = {
    "defaults_ollama_down": ({}, False),
    "defaults_ollama_up": ({}, True),
    "prod_like_cheap_pin_kimi": (
        {"TAO_CHEAP_PROVIDER": "openrouter",
         "TAO_CHEAP_REMOTE_MODEL": "~moonshotai/kimi-latest"},
        False,
    ),
    "legacy_cheap_model_anthropic": ({"TAO_CHEAP_MODEL": "claude-haiku-4-5"}, False),
    "legacy_cheap_model_openrouter": ({"TAO_CHEAP_MODEL": "meta-llama/llama-3.3-70b-instruct"}, True),
    "tier_env_and_claude_print": (
        {"TAO_TOP_MODEL": "claude-sonnet-5", "TAO_MID_USE_CLAUDE_PRINT": "1",
         "TAO_CHEAP_PROVIDER": "ollama", "TAO_CHEAP_LOCAL_MODEL": "qwen3.5:latest"},
        False,
    ),
    "per_role_overrides_and_downgrade_correction": (
        {"TAO_CHEAP_REMOTE_MODEL": "z-ai/glm-4.7-flash",
         "TAO_MODEL_INTENT_CLASSIFY": "ollama:qwen3.5:latest",
         "TAO_MODEL_PLANNER": "openrouter:z-ai/glm-4.7-flash",
         "TAO_MODEL_DEBATE_REDTEAM": "anthropic:claude-haiku-4-5",
         "TAO_MODEL_MONITOR": "no-colon-here"},
        False,
    ),
}

OTHER_ROLES = sorted(r for r in PR.ROLE_TIER if r != "margot.casual") + ["some.unknown.role"]


def snapshot() -> dict[str, dict[str, list[str]]]:
    """{scenario: {role: [provider, model_id, tier, source]}} for every non-margot role."""
    out: dict[str, dict[str, list[str]]] = {}
    ollama = _ollama_module()
    saved_env = {k: os.environ.get(k) for k in _ROUTER_ENV}
    saved_roles = {k: v for k, v in os.environ.items() if k.startswith("TAO_MODEL_")}
    saved_probe = ollama.is_reachable

    def _clear() -> None:
        for k in _ROUTER_ENV:
            os.environ.pop(k, None)
        for k in list(os.environ):
            if k.startswith("TAO_MODEL_"):
                os.environ.pop(k, None)

    try:
        for name, (env, reachable) in SCENARIOS.items():
            _clear()
            os.environ.update(env)
            ollama.is_reachable = lambda _r=reachable, **kw: _r
            out[name] = {}
            for role in OTHER_ROLES:
                pm = PR.select_provider_model(role)
                out[name][role] = [pm.provider, pm.model_id, pm.tier, pm.source]
    finally:
        _clear()
        for k, v in saved_env.items():
            if v is not None:
                os.environ[k] = v
        os.environ.update(saved_roles)
        ollama.is_reachable = saved_probe
    return out


def test_every_other_role_resolves_exactly_as_before_ra7434():
    expected = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    actual = snapshot()
    assert set(actual) == set(expected), "scenario set drifted from the fixture"
    for scenario in expected:
        assert actual[scenario] == expected[scenario], (
            f"scenario {scenario!r}: another role's routing changed; "
            "RA-7434 may only touch margot.casual"
        )


# ── margot.casual: the free ladder ──────────────────────────────────────────

FREE_LADDER = (
    ("ollama", "gemma4:latest"),
    ("openrouter", "google/gemma-4-26b-a4b-it:free"),
    ("openrouter", "z-ai/glm-4.7-flash"),
)


def test_ladder_is_exactly_the_founder_ruling():
    assert PR.MARGOT_CASUAL_LADDER == FREE_LADDER
    for prov, model in PR.MARGOT_CASUAL_LADDER:
        assert PR._margot_casual_refusal(prov, model) is None


def test_step1_ollama_when_base_url_configured_and_reachable(monkeypatch):
    monkeypatch.setenv("OLLAMA_BASE_URL", "http://ollama.local:11434/v1")
    monkeypatch.setattr(_ollama_module(), "is_reachable", lambda **kw: True)
    pm = PR.select_provider_model("margot.casual")
    assert (pm.provider, pm.model_id) == ("ollama", "gemma4:latest")
    assert pm.source == "ladder-step-1"
    assert pm.tier == "cheap"


def test_step1_prefers_margot_ollama_base_url_and_threads_it_to_the_call(monkeypatch, tmp_path):
    """Round-2 P1: Railway's start guard strips OLLAMA_BASE_URL from every work
    lane, so step 1 has its own key. The probe AND the call must target it."""
    import asyncio  # noqa: PLC0415
    import types  # noqa: PLC0415
    monkeypatch.setenv("BUDGET_TRACKER_LOG_PATH", str(tmp_path / "llm-cost.jsonl"))
    monkeypatch.setenv("MARGOT_OLLAMA_BASE_URL", "http://margot-ollama:11434/v1")
    seen: dict = {}

    def is_reachable(**kw):
        seen["probe"] = kw
        return True

    async def call(*, prompt, model_id, timeout_s=120, role="", session_id="", base_url=None):
        seen["call"] = (model_id, base_url)
        return 0, "hi from gemma", 0.0, None

    monkeypatch.setitem(sys.modules, "app.server.provider_ollama",
                        types.SimpleNamespace(is_reachable=is_reachable, call=call))
    pm = PR.select_provider_model("margot.casual")
    assert pm.source == "ladder-step-1"
    assert seen["probe"] == {"base_url": "http://margot-ollama:11434/v1"}
    rc, text, _cost, _err = asyncio.run(PR.run_via_provider("hi", role="margot.casual"))
    assert (rc, text) == (0, "hi from gemma")
    assert seen["call"] == ("gemma4:latest", "http://margot-ollama:11434/v1")


def test_step2_when_ollama_base_url_unset_even_if_probe_is_up(monkeypatch):
    """Railway has no OLLAMA_BASE_URL; a stray localhost probe must not pick Ollama."""
    monkeypatch.setattr(_ollama_module(), "is_reachable", lambda **kw: True)
    pm = PR.select_provider_model("margot.casual")
    assert (pm.provider, pm.model_id) == ("openrouter", "google/gemma-4-26b-a4b-it:free")
    assert pm.source == "ladder-step-2"


def test_step2_when_ollama_configured_but_unreachable(monkeypatch):
    monkeypatch.setenv("OLLAMA_BASE_URL", "http://ollama.local:11434/v1")
    pm = PR.select_provider_model("margot.casual")
    assert pm.source == "ladder-step-2"


def test_ladder_ignores_every_tao_cheap_knob(monkeypatch):
    """The Kimi bill came from TAO_CHEAP_REMOTE_MODEL. This role no longer reads it."""
    monkeypatch.setenv("TAO_CHEAP_PROVIDER", "openrouter")
    monkeypatch.setenv("TAO_CHEAP_REMOTE_MODEL", "~moonshotai/kimi-latest")
    monkeypatch.setenv("TAO_CHEAP_LOCAL_MODEL", "qwen3.5:latest")
    monkeypatch.setenv("TAO_CHEAP_MODEL", "claude-haiku-4-5")
    pm = PR.select_provider_model("margot.casual")
    assert (pm.provider, pm.model_id) == ("openrouter", "google/gemma-4-26b-a4b-it:free")
    assert pm.source == "ladder-step-2"


def test_override_env_is_honoured_when_free(monkeypatch):
    monkeypatch.setenv("TAO_MODEL_MARGOT_CASUAL", "openrouter:nvidia/nemotron-3-super-120b-a12b:free")
    pm = PR.select_provider_model("margot.casual")
    assert (pm.provider, pm.model_id) == ("openrouter", "nvidia/nemotron-3-super-120b-a12b:free")
    assert pm.source == "env:TAO_MODEL_MARGOT_CASUAL"


def test_malformed_override_falls_to_ladder(monkeypatch):
    monkeypatch.setenv("TAO_MODEL_MARGOT_CASUAL", "no-colon-here")
    pm = PR.select_provider_model("margot.casual")
    assert pm.source == "ladder-step-2"


@pytest.mark.parametrize("spec", [
    "openrouter:~moonshotai/kimi-latest",
    "openrouter:moonshotai/kimi-k2",
    "openrouter:~anthropic/claude-sonnet-latest",
    "openrouter:anthropic/claude-haiku-4-5",
    "anthropic:claude-haiku-4-5",
    "claude_print:sonnet",
    "ollama:Kimi-local",
])
def test_refused_override_fails_closed(monkeypatch, spec):
    monkeypatch.setenv("TAO_MODEL_MARGOT_CASUAL", spec)
    with pytest.raises(PR.RefusedModelError) as exc_info:
        PR.select_provider_model("margot.casual")
    msg = str(exc_info.value)
    assert "margot.casual" in msg
    assert "TAO_MODEL_MARGOT_CASUAL" in msg
    assert "RA-7434" in msg


# ── run_via_provider: refusal is an error tuple, never a raise ──────────────
#
# margot_bot._call_llm wraps run_via_provider in `except Exception` and falls
# back to a DIRECT Anthropic call. A raised refusal would therefore route the
# role onto the very model the ruling forbids. The refusal must come back as
# (rc=1, error) so the bot reports "unavailable" instead.


def _fake_provider(name: str, calls: list, responses: list):
    import types  # noqa: PLC0415

    async def call(*, prompt, model_id, timeout_s=120, role="", session_id="", **kw):
        calls.append((name, model_id))
        return responses.pop(0)

    return types.SimpleNamespace(call=call)


@pytest.fixture
def cost_log(monkeypatch, tmp_path):
    monkeypatch.setenv("BUDGET_TRACKER_LOG_PATH", str(tmp_path / "llm-cost.jsonl"))
    return tmp_path / "llm-cost.jsonl"


def test_run_via_provider_refusal_returns_error_tuple(monkeypatch, cost_log):
    import asyncio  # noqa: PLC0415
    monkeypatch.setenv("TAO_MODEL_MARGOT_CASUAL", "openrouter:~moonshotai/kimi-latest")
    calls: list = []
    monkeypatch.setitem(sys.modules, "app.server.provider_openrouter", _fake_provider("openrouter", calls, []))
    monkeypatch.setitem(sys.modules, "app.server.session_sdk", _fake_provider("anthropic", calls, []))
    rc, text, cost, err = asyncio.run(PR.run_via_provider("hi", role="margot.casual"))
    assert rc == 1 and text == "" and cost == 0.0
    assert err.startswith("margot_casual_refused:")
    assert "kimi" in err
    assert calls == [], "a refused model must never be called, nor any fallback"
    assert not cost_log.exists()


def test_run_via_provider_walks_the_ladder_on_failure(monkeypatch, cost_log):
    import asyncio  # noqa: PLC0415
    monkeypatch.setenv("OLLAMA_BASE_URL", "http://ollama.local:11434/v1")
    monkeypatch.setattr(_ollama_module(), "is_reachable", lambda **kw: True)
    calls: list = []
    monkeypatch.setitem(sys.modules, "app.server.provider_ollama", _fake_provider(
        "ollama", calls, [(1, "", 0.0, "ollama_call_raised: refused")]))
    monkeypatch.setitem(sys.modules, "app.server.provider_openrouter", _fake_provider(
        "openrouter", calls, [(1, "", 0.0, "openrouter_http_429: free pool"), (0, "hello", 0.0, None)]))
    # is_reachable lives on the real module we just shadowed — give the fake one too
    sys.modules["app.server.provider_ollama"].is_reachable = lambda **kw: True
    rc, text, cost, err = asyncio.run(PR.run_via_provider("hi", role="margot.casual"))
    assert (rc, text, cost, err) == (0, "hello", 0.0, None)
    assert calls == [
        ("ollama", "gemma4:latest"),
        ("openrouter", "google/gemma-4-26b-a4b-it:free"),
        ("openrouter", "z-ai/glm-4.7-flash"),
    ]
    row = json.loads(cost_log.read_text().splitlines()[-1])
    assert (row["provider"], row["role"], row["model"], row["cost_usd"]) == (
        "openrouter", "margot.casual", "z-ai/glm-4.7-flash", 0.0)


def test_run_via_provider_ladder_exhausted_is_an_error_not_a_paid_fallback(monkeypatch, cost_log):
    import asyncio  # noqa: PLC0415
    calls: list = []
    monkeypatch.setitem(sys.modules, "app.server.provider_openrouter", _fake_provider(
        "openrouter", calls, [(1, "", 0.0, "openrouter_http_429"), (1, "", 0.0, "openrouter_http_502")]))
    monkeypatch.setitem(sys.modules, "app.server.session_sdk", _fake_provider("anthropic", calls, []))
    rc, text, cost, err = asyncio.run(PR.run_via_provider("hi", role="margot.casual"))
    assert rc == 1
    assert err.startswith("margot_casual_ladder_exhausted:")
    assert [c[0] for c in calls] == ["openrouter", "openrouter"]


def test_run_via_provider_override_is_a_single_attempt(monkeypatch, cost_log):
    import asyncio  # noqa: PLC0415
    monkeypatch.setenv("TAO_MODEL_MARGOT_CASUAL", "openrouter:nvidia/nemotron-3-super-120b-a12b:free")
    calls: list = []
    monkeypatch.setitem(sys.modules, "app.server.provider_openrouter", _fake_provider(
        "openrouter", calls, [(1, "", 0.0, "openrouter_http_429")]))
    rc, _text, _cost, err = asyncio.run(PR.run_via_provider("hi", role="margot.casual"))
    assert rc == 1
    assert calls == [("openrouter", "nvidia/nemotron-3-super-120b-a12b:free")]
