"""Offline controls for the verbatim-quote check (evals/jev_constitution/quotes.py)."""
from __future__ import annotations

from evals.jev_constitution import quotes

SOURCE = quotes.normalise("""Compression must not:

* merge responsibility and authority;
* remove the accountable owner;

It: **was generated by artificial intelligence**; is familiar.""")


def test_elided_list_quote_is_verbatim():
    assert quotes.missing_fragment("Compression must not: * merge responsibility and authority;", SOURCE) is None
    assert quotes.missing_fragment("Compression must not: ... remove the accountable owner;", SOURCE) is None
    assert quotes.missing_fragment("It: was generated by artificial intelligence; is familiar.", SOURCE) is None


def test_paraphrase_is_caught():
    assert quotes.missing_fragment("Compression must never merge responsibility", SOURCE) == \
        "Compression must never merge responsibility"


def test_fragments_out_of_order_are_caught():
    assert quotes.missing_fragment("remove the accountable owner; ... Compression must not:", SOURCE) == \
        "Compression must not:"


def test_check_reports_each_question(monkeypatch):
    monkeypatch.setattr(quotes, "read_source", lambda repo, rev, name: "Agents must not: * fabricate completion;")
    data = {"constitution": "origin/main 8eb9491b8", "questions": [
        {"id": "a", "source": "X.md:1", "quote": "Agents must not: ... fabricate completion;"},
        {"id": "b", "source": "X.md:1", "quote": "Agents must never fabricate completion"}]}
    assert quotes.check(data, "/nowhere") == {"a": None, "b": "Agents must never fabricate completion"}
