"""UNI-2652 golden journey checkers and wrapper — no live 20-minute pipeline."""
from __future__ import annotations

import io
from types import SimpleNamespace
from urllib.error import HTTPError
from urllib.request import Request

from app.server.session_push_pr import _pr_body
from scripts.golden_journey import main, run_consecutive, run_one_journey
from scripts.golden_journey_checks import (
    Check,
    gate_agrees_with_session,
    parse_smoke_output,
    pr_maps_requirement_to_change_to_test,
    probe_ready,
)


class _Resp:
    def __init__(self, status: int, body: str) -> None:
        self.status = status
        self._body = body.encode()

    def read(self) -> bytes:
        return self._body

    def __enter__(self):
        return self

    def __exit__(self, *_a) -> bool:
        return False


class FakeOpener:
    def __init__(self, mapping: dict[str, tuple[int, str]]) -> None:
        self.mapping = mapping

    def open(self, req: Request, timeout: int = 15):
        url = req.full_url
        for suffix, (code, body) in self.mapping.items():
            if url.endswith(suffix):
                if code >= 400:
                    raise HTTPError(url, code, "err", hdrs=None, fp=io.BytesIO(body.encode()))
                return _Resp(code, body)
        raise HTTPError(url, 404, "missing", hdrs=None, fp=io.BytesIO(b""))


_SMOKE_OK = (
    "[A1 PASS] session spawned: abcdef123456\n"
    "  [t+12s] PR URL: https://github.com/CleanExpo/Pi-Dev-Ops/pull/99\n"
    "━━━ RESULT: PASS ━━━\n"
)


def test_a8_passes_on_health_ready_200():
    opener = FakeOpener({"/api/health/ready": (200, '{"ok":true}')})
    check = probe_ready(opener, "https://example.test")
    assert check.ok is True
    assert "/api/health/ready" in check.detail


def test_a8_falls_through_404_to_ready_alias():
    opener = FakeOpener({"/api/health/ready": (404, ""), "/ready": (200, "ok")})
    check = probe_ready(opener, "https://example.test")
    assert check.ok is True
    assert check.detail.startswith("/ready")


def test_a8_fails_on_503():
    opener = FakeOpener({"/api/health/ready": (503, "clone failed")})
    check = probe_ready(opener, "https://example.test")
    assert check.ok is False
    assert "503" in check.detail


def test_a9_complete_requires_shipped():
    ok = gate_agrees_with_session({"shipped": True}, {"status": "complete"})
    bad = gate_agrees_with_session({"shipped": False}, {"status": "complete"})
    assert ok.ok is True
    assert bad.ok is False


def test_a9_failed_must_not_be_shipped():
    ok = gate_agrees_with_session({"push_ok": False}, {"status": "failed"})
    bad = gate_agrees_with_session({"push_ok": True}, {"status": "failed"})
    assert ok.ok is True
    assert bad.ok is False


def test_a9_rejects_missing_gate_flag():
    check = gate_agrees_with_session({}, {"status": "complete"})
    assert check.ok is False


def test_a10_accepts_requirement_change_test_in_order():
    body = "## Requirement\nadd the helper\n\n## Change\nscripts/x.py\n\n## Test\npytest tests/test_x.py\n"
    assert pr_maps_requirement_to_change_to_test(body).ok is True


def test_a10_rejects_the_old_session_blurb():
    old = (
        "Autonomous Pi-CEO session `abc`.\n\n"
        "Evaluator score: 8/10 @ 70% confidence.\n\n"
        "🤖 Generated by Pi-CEO"
    )
    assert pr_maps_requirement_to_change_to_test(old).ok is False


def test_a10_rejects_empty_change_section():
    body = "## Requirement\nbrief\n\n## Change\n\n## Test\npytest\n"
    assert pr_maps_requirement_to_change_to_test(body).ok is False


def test_pr_body_helper_satisfies_a10():
    session = SimpleNamespace(
        id="sid1",
        plan="Add a one-line comment to send_telegram.py",
        modified_files=["scripts/send_telegram.py"],
        evaluator_score=8.2,
        tests_passed=True,
    )
    assert pr_maps_requirement_to_change_to_test(_pr_body(session)).ok is True


def test_parse_smoke_output_reads_sid_and_pr():
    cap = parse_smoke_output(_SMOKE_OK)
    assert cap.sid == "abcdef123456"
    assert cap.pr_url == "https://github.com/CleanExpo/Pi-Dev-Ops/pull/99"
    assert cap.smoke_passed is True


def _hooks(smoke_text: str = _SMOKE_OK, smoke_code: int = 0):
    def smoke():
        print(smoke_text, end="")
        return smoke_code

    return {
        "smoke_fn": smoke,
        "ready_fn": lambda _s: Check("A8", True, "fixture"),
        "session_fn": lambda _s, cap: gate_agrees_with_session(
            {"shipped": True}, {"status": "complete"}
        ),
        "pr_body_fn": lambda _c: pr_maps_requirement_to_change_to_test(
            "## Requirement\nr\n\n## Change\nc\n\n## Test\nt\n"
        ),
    }


def test_five_consecutive_mocked_journeys_pass():
    assert run_consecutive(5, **_hooks()) == 0


def test_consecutive_stops_on_first_failure():
    calls = {"n": 0}

    def smoke():
        calls["n"] += 1
        print(_SMOKE_OK, end="")
        return 1 if calls["n"] == 2 else 0

    hooks = _hooks()
    hooks["smoke_fn"] = smoke
    assert run_consecutive(5, **hooks) == 1
    assert calls["n"] == 2


def test_one_journey_fails_closed_when_a8_is_red():
    hooks = _hooks()
    hooks["ready_fn"] = lambda _s: Check("A8", False, "503")
    assert run_one_journey(**hooks) == 1


def test_main_plant_failure_alone_does_not_need_a_password():
    assert main(["--plant-failure"]) == 0


def test_main_live_run_without_password_is_config_error(monkeypatch):
    import scripts.golden_journey as gj

    monkeypatch.setattr(gj, "PASSWORD", "")
    assert main(["--runs", "1"]) == 2
