#!/usr/bin/env python3
"""Regenerate library/INDEX.md from the vendored sub-skill frontmatter.

Run after refresh.sh pulls a new upstream snapshot. Keeps the router thin:
SKILL.md never lists 148 skills, it points here and greps.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
LIB = ROOT / "library"


def frontmatter(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return None, None
    block = match.group(1)
    name = re.search(r"^name:\s*(.+?)\s*$", block, re.MULTILINE)
    # description may be folded across lines until the next top-level key
    desc = re.search(
        r"^description:\s*(.+?)(?=\n[a-zA-Z_-]+:|\Z)", block, re.MULTILINE | re.DOTALL
    )
    name = name.group(1).strip() if name else path.parent.name
    desc = " ".join(desc.group(1).split()) if desc else ""
    return name, desc


def main():
    rows = []
    for skill in sorted(LIB.iterdir()):
        md = skill / "SKILL.md"
        if not skill.is_dir() or not md.exists():
            continue
        name, desc = frontmatter(md)
        if name is None:
            print(f"warn: no frontmatter in {md}", file=sys.stderr)
            continue
        rows.append((skill.name, desc))

    upstream = (LIB / "UPSTREAM-COMMIT").read_text().strip()[:12]
    out = [
        "# nexus-scientific — sub-skill index",
        "",
        "Generated by `build-index.py`. Do not hand-edit.",
        f"Upstream: K-Dense-AI/scientific-agent-skills @ `{upstream}` — {len(rows)} skills.",
        "",
        "Route by grepping this file, then read the ONE matching",
        "`library/<dir>/SKILL.md` and follow it. Never read more than you need.",
        "",
        "| dir | what it does |",
        "|---|---|",
    ]
    for dirname, desc in rows:
        desc = desc.replace("|", "/")
        if len(desc) > 300:
            desc = desc[:297].rstrip() + "..."
        out.append(f"| `{dirname}` | {desc} |")
    out.append("")

    (LIB / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {LIB / 'INDEX.md'} — {len(rows)} skills")


if __name__ == "__main__":
    main()
