// app/api/actions/route.ts — generates deliverables from analysis results
export const dynamic = "force-dynamic";
export const maxDuration = 120;

import { NextRequest, NextResponse } from "next/server";
import { makeClient, getAnalysisMode, SYSTEM } from "@/lib/claude";
import { makeOctokit } from "@/lib/github";
import type { AnalysisResult } from "@/lib/types";

type ActionType =
  | "board_notes"
  | "github_issues"
  | "dockerfile"
  | "cowork_brief";

interface ActionBody {
  action: ActionType;
  result: Partial<AnalysisResult>;
  repoOwner?: string;
  repoName?: string;
}

function buildPrompt(action: ActionType, result: Partial<AnalysisResult>): string {
  const summary = `
Repository: ${result.repoName ?? "Unknown"}
Tech Stack: ${(result.techStack ?? []).join(", ")}
ZTE Level: ${result.zteLevel ?? "?"} (Score: ${result.zteScore ?? "?"}/60)
Quality Scores: Completeness ${result.quality?.completeness ?? "?"}/10, Code Quality ${result.quality?.codeQuality ?? "?"}/10
Executive Summary: ${result.executiveSummary ?? "Not available"}
Strengths: ${(result.strengths ?? []).join("; ")}
Weaknesses: ${(result.weaknesses ?? []).join("; ")}
Next Actions: ${(result.nextActions ?? []).join("; ")}
Sprints: ${(result.sprints ?? []).map((s) => `Sprint ${s.id}: ${s.name} (${s.items.length} items)`).join(", ")}
`.trim();

  switch (action) {
    case "board_notes":
      return `${SYSTEM}

You are generating a formal board meeting notes document.

ANALYSIS DATA:
${summary}

Generate a professional board meeting notes document in Markdown. Include:
1. Executive Summary (3-4 sentences, non-technical)
2. Current State Assessment (what exists, what works)
3. Key Risks (top 3, business impact)
4. Recommended Actions (from next actions, framed as board decisions)
5. Sprint Investment Summary (total effort, expected outcomes)
6. ZTE Maturity Score (explain what Level ${result.zteLevel ?? "?"} means for the business)

Be direct. Write for a board audience — no jargon. Use tables where appropriate.`;

    case "cowork_brief":
      return `${SYSTEM}

You are generating a CoWork session brief for the Claude Desktop CoWork feature.

ANALYSIS DATA:
${summary}

Generate a structured CoWork brief that can be pasted into a Claude Desktop CoWork session. Include:
1. Project context (what was analysed, current state)
2. Priority tasks for this session (from sprint 1 items)
3. Key files to focus on (from the analysis)
4. Success criteria (what "done" looks like)
5. Specific instructions for the Claude agent

Format it as actionable instructions Claude can immediately execute.`;

    case "dockerfile":
      return `${SYSTEM}

Generate a production-ready Dockerfile for this repository.

ANALYSIS DATA:
${summary}

Generate a complete, optimised Dockerfile with:
1. Appropriate base image for the tech stack
2. Multi-stage build if applicable
3. Security best practices (non-root user, minimal image)
4. Health check
5. Correct port exposure
6. Environment variable placeholders

Also include a docker-compose.yml for local development.
Output ONLY the files, no explanation.`;

    default:
      return `${SYSTEM}\n\nAnalysis:\n${summary}\n\nSummarise the key findings.`;
  }
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: ActionBody;
  try {
    body = await req.json() as ActionBody;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { action, result, repoOwner, repoName } = body;

  // ── GitHub Issues — handled separately (no Claude needed) ─────────────────
  if (action === "github_issues") {
    const token = process.env.GITHUB_TOKEN?.trim();
    if (!token || !repoOwner || !repoName) {
      return NextResponse.json({ error: "GitHub token, repoOwner, and repoName required" }, { status: 400 });
    }

    const octokit = makeOctokit(token);
    const gaps = result.nextActions ?? [];
    const created: string[] = [];

    for (const gap of gaps.slice(0, 5)) {
      try {
        const issue = await octokit.issues.create({
          owner: repoOwner,
          repo: repoName,
          title: gap.slice(0, 100),
          body: `**Pi CEO Analysis Finding**\n\n${gap}\n\n---\n*Generated by [Pi CEO](https://dashboard-unite-group.vercel.app) on ${new Date().toISOString().slice(0, 10)}*`,
          labels: ["pi-ceo", "enhancement"],
        });
        created.push(issue.data.html_url);
      } catch { /* skip individual failures */ }
    }

    return NextResponse.json({
      output: `Created ${created.length} GitHub issues:\n${created.join("\n")}`,
    });
  }

  // ── Claude-generated actions (board_notes, dockerfile, cowork_brief) ───────
  const prompt = buildPrompt(action, result);

  try {
    const client = makeClient();

    if (getAnalysisMode() === "cli" || !client) {
      // CLI fallback: run claude -p
      const { spawn } = await import("child_process");
      return new Promise((resolve) => {
        const child = spawn("claude", ["-p", prompt, "--model", process.env.ANALYSIS_MODEL ?? "claude-sonnet-4-6", "--output-format", "text"], {
          env: { ...process.env },
        });
        let output = "";
        child.stdout.on("data", (d: Buffer) => { output += d.toString(); });
        child.on("close", () => {
          resolve(NextResponse.json({ output }));
        });
        child.on("error", () => {
          resolve(NextResponse.json({ error: "claude CLI not available" }, { status: 500 }));
        });
      });
    }

    const response = await client.messages.create({
      model: process.env.ANALYSIS_MODEL ?? "claude-sonnet-4-6",
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }],
    });

    const block = response.content[0];
    const output = block.type === "text" ? block.text : "";
    return NextResponse.json({ output });

  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Action failed" }, { status: 500 });
  }
}
